name: "preprocess"
backend: "python"
max_batch_size: 8

input [
  {
    name: "IMAGE"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 3, 128, 128 ]
  }
]

instance_group [ { kind: KIND_CPU } ]
