name: "postprocess"
backend: "python"
max_batch_size: 8

input [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 3, 128, 128 ]
  }
]
output [
  {
    name: "OUTPUT_IMAGE"
    data_type: TYPE_UINT8
    dims: [ 128, 128, 3 ]
  }
]

instance_group [ { kind: KIND_CPU } ]
